const mongoose = require('mongoose');
const Course = require('./models/course');


mongoose.connect('mongodb://localhost:27017/scheduleBuild', {
        useNewUrlParser: true,
        useUnifiedTopology: true
    })
    .then(() => {
        console.log("MONGO CONNECTION WORKS");
    })
    .catch((err => {
        console.log("OH NO MONGO ERROR");
        console.log(err);
    }))

    const classProducts = [{
        subject: 'CSE',
        course: 101,
        component: 'LEC',
        section: 1,
        days: 'MWF',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Kevin McDonnell',
        enrlCap: 210,
        waitCap: 70
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 01,
        days: 'M',
        startTime: '12:00 PM',
        endTime: '12:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 02,
        days: 'M',
        startTime: '01:00 PM',
        endTime: '01:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 03,
        days: 'TU',
        startTime: '04:00 PM',
        endTime: '04:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 04,
        days: 'TU',
        startTime: '05:30 PM',
        endTime: '06:23 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 05,
        days: 'W',
        startTime: '12:00 PM',
        endTime: '12:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 06,
        days: 'W',
        startTime: '04:00 PM',
        endTime: '04:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 101,
        component: 'LAB',
        section: 07,
        days: 'TH',
        startTime: '04:00 PM',
        endTime: '04:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Kevin McDonnell',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Paul Fodor',
        enrlCap: 120,
        waitCap: 44
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 01,
        days: 'MW',
        startTime: '07:00 PM',
        endTime: '08:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Paul Fodor',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 02,
        days: 'TUTH',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Paul Fodor',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 03,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Paul Fodor',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 04,
        days: 'TUTH',
        startTime: '05:30 PM',
        endTime: '06:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Paul Fodor',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LEC',
        section: 2,
        days: 'TUTH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Praveen Tripathi',
        enrlCap: 120,
        waitCap: 33
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 07,
        days: 'MW',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Praveen Tripathi',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 08,
        days: 'MW',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Praveen Tripathi',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 09,
        days: 'MW',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Praveen Tripathi',
        enrlCap: 30,
        waitCap: 11
    },

    {
        subject: 'CSE',
        course: 114,
        component: 'LAB',
        section: 10,
        days: 'MW',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2116',
        instructor: 'Praveen Tripathi',
        enrlCap: 30,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 160,
        component: 'LEC',
        section: 01,
        days: 'MW',
        startTime: '05:30 PM',
        endTime: '06:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Paul Fodor',
        enrlCap: 50,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 161,
        component: 'LAB',
        section: 01,
        days: 'MW',
        startTime: '07:00 PM',
        endTime: '08:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Paul Fodor',
        enrlCap: 35,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'LEC',
        section: 01,
        days: 'TUTH',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Ahmad Esmaili',
        enrlCap: 120,
        waitCap: 30
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 01,
        days: 'RETH',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Ahmad Esmaili',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 02,
        days: 'RETU',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Ahmad Esmaili',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 03,
        days: 'RETU',
        startTime: '04:00 PM',
        endTime: '04:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Ahmad Esmaili',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 04,
        days: 'RETH',
        startTime: '04:00 PM',
        endTime: '04:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Ahmad Esmaili',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'LEC',
        section: 2,
        days: 'MWF',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Pramod Ganapathi',
        enrlCap: 120,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 06,
        days: 'RECF',
        startTime: '02:30 PM',
        endTime: '03:23 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 0,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 07,
        days: 'RECM',
        startTime: '02:30 PM',
        endTime: '03:23 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 08,
        days: 'RECW',
        startTime: '02:30 PM',
        endTime: '03:23 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 214,
        component: 'REC',
        section: 09,
        days: 'RECM',
        startTime: '03:30 PM',
        endTime: '04:23 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 30,
        waitCap: 5
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Christopher Kane',
        enrlCap: 120,
        waitCap: 40
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 01,
        days: 'RECM',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Christopher Kane',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 02,
        days: 'RECW',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Christopher Kane',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: ' REC',
        section: 03,
        days: 'RECM',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Christopher Kane',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 04,
        days: 'RECW',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Christopher Kane',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'LEC',
        section: 02,
        days: 'MW',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Pramod Ganapathi',
        enrlCap: 120,
        waitCap: 40
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 06,
        days: ' RECW',
        startTime: '01:00 PM',
        endTime: '01:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 07,
        days: 'RECM',
        startTime: '11:00 AM',
        EnTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2129',
        instructor: 'Pramod Ganapathi',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 08,
        days: 'RECW',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-2',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 215,
        component: 'REC',
        section: 09,
        days: 'RECF',
        startTime: '09:00 AM',
        endTime: '09:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2114',
        instructor: 'Pramod Ganapathi',
        enrlCap: 0,
        waitCap: 0
    },


    {
        subject: 'CSE',
        course: 216,
        component: 'LEC',
        section: 1,
        days: 'MW',
        startTime: '05:30 PM',
        endTime: '06:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Ritwik Banerjee',
        enrlCap: 180,
        waitCap: 25
    },

    {
        subject: 'CSE',
        course: 216,
        component: 'REC',
        section: 01,
        days: 'RETU',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Ritwik Banerjee',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 216,
        component: 'REC',
        section: 02,
        days: 'RETH',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Ritwik Banerjee',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 216,
        component: 'REC',
        section: 03,
        days: 'RETU',
        startTime: '09:00 AM',
        endTime: '09:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Ritwik Banerjee',
        enrlCap: 30,
        waitCap: 10
    },


    {
        subject: 'CSE',
        course: 216,
        component: 'REC',
        section: 04,
        days: 'RETU',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Ritwik Banerjee',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 216,
        component: 'REC',
        section: 05,
        days: 'RETH',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Ritwik Banerjee',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 216,
        component: 'REC',
        section: 06,
        days: 'RETU',
        startTime: '12:00 PM',
        endTime: '12:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Ritwik Banerjee',
        enrlCap: 30,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Joydeep Mitra',
        enrlCap: 180,
        waitCap: 48
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'REC',
        section: 01,
        days: 'RECM',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Joydeep Mitra',
        enrlCap: 30,
        waitCap: 8
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'REC',
        section: 02,
        days: 'RECW',
        startTime: '10:00 AM',
        endTime: '10:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Joydeep Mitra',
        enrlCap: 30,
        waitCap: 8
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'REC',
        section: 03,
        days: 'RECM',
        startTime: '11:00 AM',
        endTime: '11:53 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Joydeep Mitra',
        enrlCap: 30,
        waitCap: 8
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'REC',
        section: 05,
        days: 'RECM',
        startTime: '12:00 PM',
        endTime: '12:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Joydeep Mitra',
        enrlCap: 30,
        waitCap: 8
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'REC',
        section: 06,
        days: 'RECW',
        startTime: '12:00 PM',
        endTime: '12:53 PM',
        from: '25-Jan-21',
        till: '19-May-2',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Joydeep Mitra',
        enrlCap: 30,
        waitCap: 8
    },

    {
        subject: 'CSE',
        course: 220,
        component: 'REC',
        section: 07,
        days: 'RECM',
        startTime: '02:30 PM',
        endTime: '03:23 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '115',
        instructor: 'Joydeep Mitra',
        enrlCap: 30,
        waitCap: 8
    },

    {
        subject: 'CSE',
        course: 300,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'TBA',
        enrlCap: 35,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 300,
        component: 'LEC',
        section: 2,
        days: 'TUTH',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'TBA',
        enrlCap: 35,
        waitCap: 0
    },


    {
        subject: 'CSE',
        course: 300,
        component: 'LEC',
        section: 3,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'TBA',
        enrlCap: 35,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 300,
        component: 'LEC',
        section: 4,
        days: 'TUTH',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'TBA',
        enrlCap: 35,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 300,
        component: 'LEC',
        section: 5,
        days: 'TUTH',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'TBA',
        enrlCap: 35,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 300,
        component: 'LEC',
        section: 6,
        days: 'MW',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'TBA',
        enrlCap: 35,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 303,
        component: 'LEC',
        section: 1,
        days: 'MWF',
        startTime: '12:00 PM',
        endTime: '12:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Pramod Ganapathi',
        enrlCap: 250,
        waitCap: 30
    },

    {
        subject: 'CSE',
        course: 306,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Eugene Stark',
        enrlCap: 150,
        waitCap: 20
    },

    {
        subject: 'CSE',
        course: 307,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Joydeep Mitra',
        enrlCap: 80,
        waitCap: 15
    },

    {
        subject: 'CSE',
        course: 310,
        component: 'LEC',
        section: 1,
        days: 'MW',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Aruna Balasubramanian',
        enrlCap: 200,
        waitCap: 50
    },

    {
        subject: 'CSE',
        course: 311,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2120',
        instructor: 'Ahmad Esmaili',
        enrlCap: 25,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 312,
        component: 'LEC',
        section: 1,
        days: 'MW',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Anthony Scarlatos',
        enrlCap: 120,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 312,
        component: 'LEC',
        section: 2,
        days: 'MW',
        startTime: '07:00 PM',
        endTime: '08:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Michael Tashbook',
        enrlCap: 120,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 316,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Richard McKenna',
        enrlCap: 120,
        waitCap: 20
    },

    {
        subject: 'CSE',
        course: 320,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Eugene Stark',
        enrlCap: 250,
        waitCap: 30
    },

    {
        subject: 'CSE',
        course: 327,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Dimitrios Samaras',
        enrlCap: 40,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 334,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'COMPUTER SCI',
        room: '2205',
        instructor: 'Anthony Scarlatos',
        enrlCap: 11,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 337,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '05:30 PM',
        endTime: '06:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Michael Tashbook',
        enrlCap: 100,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 351,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Praveen Tripathi',
        enrlCap: 100,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 352,
        component: 'LEC',
        section: 1,
        days: 'HTBA',
        startTime: '01:00 AM',
        endTime: '01:00 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 0,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Niranjan Balasubramanian',
        enrlCap: 100,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 354,
        component: 'LEC',
        section: 1,
        days: 'MW',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Hansen Schwartz',
        enrlCap: 100,
        waitCap: 20
    },

    {
        subject: 'CSE',
        course: 371,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Anita Wasilewska',
        enrlCap: 60,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 373,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Rezaul Chowdhury',
        enrlCap: 120,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 376,
        component: 'LEC',
        section: 1,
        days: 'MW',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '120',
        instructor: 'Erez Zadok',
        enrlCap: 80,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 380,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Richard McKenna',
        enrlCap: 100,
        waitCap: 30
    },

    {
        subject: 'CSE',
        course: 385,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Michael Bender',
        enrlCap: 60,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 385,
        component: 'REC',
        section: 01,
        days: 'RETH',
        startTime: '02:00 PM',
        endTime: ' 02:53 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 53,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Michael Bender',
        enrlCap: 60,
        waitCap: 0,
    },

    {
        subject: 'CSE',
        course: 416,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '07:00 PM',
        endTime: '08:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Robert Kelly',
        enrlCap: 70,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 416,
        component: 'LEC',
        section: 2,
        days: 'TUTH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Scott Stoller',
        enrlCap: 70,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 506,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '08:30 AM',
        endTime: '09:50 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Dongyoon Lee',
        enrlCap: 150,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 512,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Minh Hoai Nguyen',
        enrlCap: 150,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 526,
        component: 'LEC',
        section: 1,
        days: 'MF',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Yanhong Liu',
        enrlCap: 100,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 527,
        component: 'LEC',
        section: 1,
        days: 'MW',
        startTime: '07:00 PM',
        endTime: '08:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Haibin Ling',
        enrlCap: 120,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 532,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '05:30 PM',
        endTime: '06:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Michael Kifer',
        enrlCap: 150,
        waitCap: 34
    },

    {
        subject: 'CSE',
        course: 540,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '02:30 PM',
        endTime: '03:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Omkant Pandey',
        enrlCap: 150,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 541,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Anita Wasilewska',
        enrlCap: 120,
        waitCap: 15
    },

    {
        subject: 'CSE',
        course: 544,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '01:00 PM',
        endTime: '02:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Anshul Gandhi',
        enrlCap: 100,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 545,
        component: 'LEC',
        section: 01,
        days: 'TUTH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Hansen Schwartz',
        enrlCap: 150,
        waitCap: 28
    },

    {
        subject: 'CSE',
        course: 548,
        component: 'LEC',
        section: 01,
        days: 'MW',
        startTime: '04:00 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Rezaul Chowdhury',
        enrlCap: 180,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 550,
        component: 'SEM',
        section: 01,
        days: 'TU',
        startTime: '10:31 AM',
        endTime: '11:30 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 59,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '120',
        instructor: 'Predrag Krstic',
        enrlCap: 20,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 550,
        component: 'LEC',
        section: 01,
        days: 'TU',
        startTime: '09:30 AM',
        endTime: '10:30 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 60,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '120',
        instructor: 'Predrag Krstic',
        enrlCap: 20,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 555,
        component: 'LEC',
        section: 01,
        days: 'TUTH',
        startTime: '10:00 AM',
        endTime: '11:20 AM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Joseph Mitchell',
        enrlCap: 60,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 564,
        component: 'LEC',
        section: 1,
        days: 'TUTH',
        startTime: '07:00 PM',
        endTime: '08:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Klaus Mueller',
        enrlCap: 250,
        waitCap: 6
    },

    {
        subject: 'CSE',
        course: 566,
        component: 'LEC',
        section: 1,
        days: 'W',
        startTime: '02:30 PM',
        endTime: '05:20 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 170,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '220',
        instructor: 'Arie Kaufman',
        enrlCap: 30,
        waitCap: 0
    },

    {
        subject: 'CSE',
        course: 600,
        component: 'SEM',
        section: 01,
        days: 'F',
        startTime: '02:30 PM',
        endTime: '03:30 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 60,
        instructionMode: 'In Person',
        building: 'TBA',
        room: '120',
        instructor: 'Samir Das',
        enrlCap: 80,
        waitCap: 10
    },

    {
        subject: 'CSE',
        course: 645,
        component: 'SEM',
        section: 01,
        days: 'TH',
        startTime: '11:30 AM',
        endTime: '12:50 PM',
        from: '25-Jan-21',
        till: '19-May-21',
        duration: 80,
        instructionMode: 'In Person',
        building: 'TBA',
        room: 'TBA',
        instructor: 'Paul Fodor, Michael Kifer, C Ramakrishnan, Yanhong Liu',
        enrlCap: 30,
        waitCap: 0,
    },
]


Course.insertMany(classProducts)
    .then(res => {
        console.log(res)
    })
    .catch(e => {
        console.log(e)
    })